name: rc_clone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.41+41

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  html: ^0.15.0
  camera: ^0.9.8
  location: ^4.4.0
  sqflite: ^2.0.2+1
  flutter_svg: ^1.0.3
  flutter_bloc: ^8.0.1
  maps_launcher: ^2.0.1
  url_launcher: ^6.0.20
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2
  flutter_sound_lite: ^8.5.0
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.8
  ed_screen_recorder: ^0.0.10
  flutter_screenutil: ^5.0.0+2
  font_awesome_flutter: ^9.2.0
  simple_connection_checker: ^0.2.1
  syncfusion_flutter_pdfviewer: ^20.1.61-beta
  omeet_screen_capture:
    path: ./omeet_screen_capture
  jitsi_meet:
    git:
      url: https://github.com/dispersik/jitsi_meet_fork
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
   - family: Nunito
     fonts:
       - asset: fonts/Nunito/Nunito-Regular.ttf
       - asset: fonts/Nunito/Nunito-SemiBold.ttf
         weight: 600
       - asset: fonts/Nunito/Nunito-Bold.ttf
         weight: 700

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
